### PR TITLE
Normalize mac_address

### PR DESCRIPTION
**Pull request by logankimmel**

### CODE REVIEW

**Comment by ripienaar** [comment]
seems good to me, can you think of anything this might break elsewhere @gavin-scott

**Comment by gavin-scott** [comment]
Yeah, I'm worried existing asm-deployer cisconexus flows will break with this change. I'm thinking we should hold this until we are have fully implemented cisconexus switch configuration in the new flow?

**Comment by gavin-scott** [comment]
Hold until cisco switches are working in the new switch config flow. May want to just include this as part of those PRs.

**Comment by gavin-scott** [comment]
@logankimmel please rebase

**Comment by logankimmel** [comment]
@gavin-scott This is fixed

**Pull request merged**
