### PR TITLE
Changes made to upgrade firmware for Cisco switches

### PR DESCRIPTION
**Pull request by randhirray**
Backend Update Firmware for Cisco Switches using "Update Resources" option in the Compliance Report

### CODE REVIEW

**Comment by randhirray** [comment]
@aaronprince @gavin-scott @sushilrai @naveenhirebeeldell @saxens7 
Please review and merge

**Comment by randhirray** [comment]
Dependent PR : https://github.com/dell-asm/asm/pull/371

**Comment by sushilrai** [comment]
@randhirray please remove all the commented code, remove unrequired debug statement and rename the methods using snake case.

Please refer existing type and provider for Cisco Nexus for your reference

**Comment by randhirray** [comment]
Have made the changes as mentioned in the review, please merge.

**Comment by randhirray** [comment]
@sushilrai Please merge

**Pull request merged**
