### PR TITLE
added snmp community strings command to get all community string

### PR DESCRIPTION
**Pull request by arunrordell**
Retrieves all snmp community strings and saves as json.

### CODE REVIEW

**Comment by gavin-scott** [comment]
Please update title and squash commits per https://confluence.gtie.dell.com/display/ASM/Github+PR+and+JIRA+Best+Practices

**Comment by ripienaar** [comment]
Please remember to add this JSON fact to asm-deployer in every provider affected so it gets decided there correctly.

**Comment by gavin-scott** [comment]
Thanks @ripienaar 

@arunrordell  here is an example: https://github.com/dell-asm/asm-deployer/blob/ac62e51166eaa91b8889390fee95baf5fe2e6cdb/lib/asm/provider/switch/base.rb#L55

**Comment by ripienaar** [comment]
Thanks Gavin don't have my computer with me so was trying to find a example on the phone and failing :)

**Comment by ripienaar** [comment]
note once https://github.com/dell-asm/asm-deployer/pull/1540 is merged this changes a bit.

This PR will add this fact handling to all switches already https://github.com/ripienaar/asm-deployer/blob/facts_on_all_providers_2/lib/asm/provider/switch/base.rb#L56

If you need to add it to any non switches you do it like this: https://github.com/ripienaar/asm-deployer/blob/facts_on_all_providers_2/lib/asm/provider/cluster/vmware.rb#L14-L18

**Pull request closed without merging**
