### PR TITLE
ASM-5569: Report remote chassis mac address correctly

### PR DESCRIPTION
**Pull request by ripienaar**
The command show lldb neigh will show the remote hostname/device name as
device id while we expect a mac address, this resulted in
remote_device_info like:

    {"interface":"Eth1/17",
     "location":"TenGigabitEthernet 0/44",
     "remote_mac":"IO:A1"}

There's a more complete command sh lldb neigh details that will show the
remote chassis id as a mac address but it's a multi line output so
requires more complex parsing

This adjusts the cisco facts accordingly, there's a small chance this
will change some reported remote ids, the same entry as above now looks
like:

    {"interface":"Eth1/17",
     "location":"TenGigabitEthernet 0/44",
     "remote_mac":"d0:67:e5:94:12:c3"}

This is a force10 switch and the mac address here is the one reported in
the force10 stack_mac facts

### CODE REVIEW

**Comment by ripienaar** [comment]
@sushilrai can you foresee any problems with this change?

**Comment by gavin-scott** [comment]
:+1: 

@sushilrai is out sick today and may not be able to look at this. I'm ok to merge it.

**Comment by ripienaar** [comment]
Yeah I think its better than before - but thought he might have some context where it might break.  If there's QA to test ASM-6022 after this we should just go ahead

**Comment by gavin-scott** [comment]
Yes, that will definitely be QA'd.

**Pull request merged**
